name: 'Strands Agent Runner'
description: 'Execute a Strands agent with the given prompts and configuration'
inputs:
  aws_role_arn:
    description: 'AWS IAM role ARN for authentication'
    required: true
  sessions_bucket:
    description: 'S3 bucket for session storage'
    required: true
  write_permission:
    description: 'If this action runs with write permission. If this is false, you should run the `strands-write-executor` action after this one with write permission.'
    required: true
    default: 'false'
  langfuse_public_key:
    description: 'Langfuse public key for telemetry (optional)'
    required: false
    default: ''
  langfuse_secret_key:
    description: 'Langfuse secret key for telemetry (optional)'
    required: false
    default: ''
  langfuse_host:
    description: 'Langfuse host URL for telemetry (optional, e.g., https://us.cloud.langfuse.com)'
    required: false
    default: 'https://us.cloud.langfuse.com'
  evals_sqs_queue_arn:
    description: 'SQS queue ARN for eval triggers (optional)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Download parsed input artifact
      uses: actions/download-artifact@v4
      with:
        name: strands-parsed-input

    - name: Read parsed input
      id: read-input
      shell: bash
      run: |
        echo "ref=$(jq -r .branch_name strands-parsed-input.json)" >> $GITHUB_OUTPUT
        echo "session_id=$(jq -r .session_id strands-parsed-input.json)" >> $GITHUB_OUTPUT
        echo "system_prompt<<EOF" >> $GITHUB_OUTPUT
        jq -r .system_prompt strands-parsed-input.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "task_prompt<<EOF" >> $GITHUB_OUTPUT
        jq -r .prompt strands-parsed-input.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    # Checkout devtools repo for scripts
    - name: Checkout devtools
      uses: actions/checkout@v5
      with:
        repository: strands-agents/devtools
        ref: main
        sparse-checkout: |
          strands-command/scripts
          strands-command/agent-sops
        path: devtools

    # Copy the devtools directory to the runner temp directory so the branch content cant overwrite the scripts executed here
    - name: Copy devtools to safe directory
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/strands-agent-runner
        cp -r devtools/strands-command ${{ runner.temp }}/strands-agent-runner/

    # Checkout the branch repo to stage the directory for the agent
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: ${{ steps.read-input.outputs.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: '${{ runner.temp }}/strands-agent-runner/strands-command/scripts/python/requirements.txt'

    - name: Install Strands Agents
      shell: bash
      run: |
        echo "📦 Installing from requirements.txt"
        uv pip install --system -r ${{ runner.temp }}/strands-agent-runner/strands-command/scripts/python/requirements.txt --quiet

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "Strands Agent"
        git config --global user.email "217235299+strands-agent@users.noreply.github.com"
        git config --global core.pager cat
        PAGER=cat

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        role-session-name: GitHubActions-StrandsAgent-${{ github.run_id }}
        aws-region: us-west-2
        mask-aws-account-id: true
        inline-session-policy: >-
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "bedrock:InvokeModelWithResponseStream",
                  "bedrock:InvokeModel"
                ],
                "Resource": "*"
              }, {
                "Effect": "Allow",
                "Action": [
                  "s3:PutObject",
                  "s3:GetObject",
                  "s3:DeleteObject"
                ],
                "Resource": [
                  "arn:aws:s3:::${{ inputs.sessions_bucket }}/*"
                ]
              }, {
                "Effect": "Allow",
                "Action": "s3:ListBucket",
                "Resource": [
                  "arn:aws:s3:::${{ inputs.sessions_bucket }}"
                ]
              }, {
                "Effect": "Allow",
                "Action": "sqs:SendMessage",
                "Resource": "${{ inputs.evals_sqs_queue_arn }}"
              }
            ]
          }


    - name: Execute strands command
      shell: bash
      env:
        # Write Permission
        GITHUB_WRITE: ${{ inputs.write_permission }}

        # GitHub Configuration
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}

        # Task Configuration
        INPUT_TASK: ${{ steps.read-input.outputs.task_prompt }}
        INPUT_SYSTEM_PROMPT: ${{ steps.read-input.outputs.system_prompt }}

        # AWS Configuration
        AWS_REGION: 'us-west-2'

        # Session Manager
        S3_SESSION_BUCKET: ${{ inputs.sessions_bucket }}
        SESSION_ID: ${{ steps.read-input.outputs.session_id }}

        # Strands Env Vars
        STRANDS_TOOL_CONSOLE_MODE: 'enabled'
        BYPASS_TOOL_CONSENT: 'true'

        # Langfuse Telemetry (optional)
        LANGFUSE_PUBLIC_KEY: ${{ inputs.langfuse_public_key }}
        LANGFUSE_SECRET_KEY: ${{ inputs.langfuse_secret_key }}
        LANGFUSE_HOST: ${{ inputs.langfuse_host }}

        # Evals Configuration (optional)
        EVALS_SQS_QUEUE_ARN: ${{ inputs.evals_sqs_queue_arn }}
      run: |
        uv run --no-project ${{ runner.temp }}/strands-agent-runner/strands-command/scripts/python/agent_runner.py "$INPUT_TASK"

    - name: Capture repository state
      shell: bash
      run: |
        mkdir -p .artifact
        if git diff --quiet HEAD@{upstream} && git diff --quiet --cached; then
          echo "📭 No changes to capture"
        else
          echo "📝 Capturing entire repository state"
          tar -czf .artifact/repository_state.tar.gz --exclude='.artifact' .
        fi

    - name: Upload repository state artifact
      uses: actions/upload-artifact@v4
      with:
        name: repository-state
        path: .artifact/repository_state.tar.gz
        retention-days: 1
        if-no-files-found: ignore

    - name: Upload artifact for write operations
      uses: actions/upload-artifact@v4
      with:
        name: write-operations
        path: .artifact/write_operations.jsonl
        retention-days: 1
        if-no-files-found: ignore
